//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtrapSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id_cliente { get; set; }
        public System.DateTime dataNascimento_cliente { get; set; }
        public string cidade_cliente { get; set; }
        public string rua_cliente { get; set; }
        public string cep_cliente { get; set; }
        public string bairro_cliente { get; set; }
        public string telefone_cliente { get; set; }
        public bool sexo_cliente { get; set; }
    }
}
