//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtrapSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fornecedor()
        {
            this.produtoes = new HashSet<produto>();
        }
    
        public int id_fornecedor { get; set; }
        public string nome_empresa { get; set; }
        public string nome_vendedor { get; set; }
        public string cidade_empresa { get; set; }
        public string cep_empresa { get; set; }
        public string cnpj_empresa { get; set; }
        public string telefone_vendedor { get; set; }
        public string telefone_empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produto> produtoes { get; set; }
    }
}
