//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtrapSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int id_produto { get; set; }
        public int id_categoria { get; set; }
        public int id_fornecedor { get; set; }
        public string codBarras { get; set; }
        public System.DateTime dataVencimento { get; set; }
        public decimal valorCompra { get; set; }
        public decimal valorRevenda { get; set; }
        public string descricao { get; set; }
        public int qnt { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual fornecedor fornecedor { get; set; }
    }
}
